# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "TVqNjptyBp1rcbB6GavbijPUiuAe2RusfnkPcDQs8dztwQNaGUcuqsK0Qv9/3IwJdOGpo+6eMttlEjY5lSSargkmgh2PPULJi4HGqZ4Lsv2Di/mRxNk9SFbpfGVwgGWkr7dPepkdVxje61fdz6VeSY58SHn1dsU/CE9aEL2+yhbkWr82i0kUyoGNfBZPPT/nxXbctiWyDdHymiplbAcH6dbn6YDkhh40PhsstXbTe3BXmpTz8SHtWeJkypfjPD6oH3HH0JkEWkkqza5NsH4HIohDXQ2+Fig3NrXCUtvCZIkQc8yKhpzTyc6ORVEZ0jQW5gDJwS+/0IPqkcp5DlhGVcR49h7tTKY2s7lHE/QlLO8fUuzEizfZoEdsqeQ/5TJAZJMlNMG2ix2euD17l5eHveLdhDAvFytTpno/V4VSSrAT5pez+iPUZMEB1g2hzrlQi39yvIMGplT0U0UoW2KeqbBgAgYnNDHwq3AK+Hu5C50MuNgprQHfAWoGK79ggnQVgq2vOJPzVhU+HQj9ULQFomq/616/WEGkq8khqikL80Fjq3T7FTaCf/iDvFkzL39jzUcdCvk7YVHCSDm/CUSOKbvaILivRFHv9L9UTyX0WgZzRBFHAS75KMsaqMun0RezSK8QNNQydh+wgfWnpBEJjDYkHrtYnX4zkBMcF3IHq34="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
