travis:
  secure:
    BINSTAR_TOKEN: E4kfq19FloA+nlCfUJaaMNnf9UHKThidYgrUGceuaqEHlCz+mxwKeHBVNVFVFweQzC3AxN2ZX3am1/SZ/fYDMlaUjegcOcGgBlhmZow1CkGIQHYEYYKI0XYEmoxhTOObmwcNTFRNFz07y72rkubmEPPQivHcka0XAIm+Uh+9X9cWfvoVsUaIGAAxqSeJrtEoBy9FzpE/222JHmcecfqN40XDIQmoLPx1s2P3HCUg98edkCovJzpAuI13/pjeNI19LG1SGxYmovl8AlXBCO1Bflsu7tohSQMN7eXPHKHQ/Z7ye0cbmb24tYWJTSlYKqvxufkFVC9m9ASZ+m3k4FIp38kHtbUEXBnTkRgQ9xAP6rSUCgceTA73cgl9X9Ds/ZvGAYrWrqKSOtHFBTYPrDt79UFs8D7ZQHXl/rP9GDEaDDKHLH2c0yMLOKZctvNqf7kCYkakwd22Z2Ra6Es0aqd7K7/DsJPocFk9jSu2O3TBN8t7RHKansUgvewqqSAq9iBEpk2ZjjLZgzKSEA0aPuSscjs9ylkeddW/nqOegCbPvUflFMAGlbpW/jtPoHyijtgUarBXBwNjZMFrb2xgRfp+PUs3u5EcQ6GEwtijDqefJB656KGthtp0DfHCUEd+5IQl+3H6BEXxuYbMgAIufClt7xKc7AFztJJ8rr73d/xVZSw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
