travis:
  secure:
    BINSTAR_TOKEN: TVqNjptyBp1rcbB6GavbijPUiuAe2RusfnkPcDQs8dztwQNaGUcuqsK0Qv9/3IwJdOGpo+6eMttlEjY5lSSargkmgh2PPULJi4HGqZ4Lsv2Di/mRxNk9SFbpfGVwgGWkr7dPepkdVxje61fdz6VeSY58SHn1dsU/CE9aEL2+yhbkWr82i0kUyoGNfBZPPT/nxXbctiWyDdHymiplbAcH6dbn6YDkhh40PhsstXbTe3BXmpTz8SHtWeJkypfjPD6oH3HH0JkEWkkqza5NsH4HIohDXQ2+Fig3NrXCUtvCZIkQc8yKhpzTyc6ORVEZ0jQW5gDJwS+/0IPqkcp5DlhGVcR49h7tTKY2s7lHE/QlLO8fUuzEizfZoEdsqeQ/5TJAZJMlNMG2ix2euD17l5eHveLdhDAvFytTpno/V4VSSrAT5pez+iPUZMEB1g2hzrlQi39yvIMGplT0U0UoW2KeqbBgAgYnNDHwq3AK+Hu5C50MuNgprQHfAWoGK79ggnQVgq2vOJPzVhU+HQj9ULQFomq/616/WEGkq8khqikL80Fjq3T7FTaCf/iDvFkzL39jzUcdCvk7YVHCSDm/CUSOKbvaILivRFHv9L9UTyX0WgZzRBFHAS75KMsaqMun0RezSK8QNNQydh+wgfWnpBEJjDYkHrtYnX4zkBMcF3IHq34=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
